setwd("C:/Users/alex/Desktop/Exploratory Data Analysis")
options(stringsAsFactors = F)
my_data <- read.table("household_power_consumption.txt", header=T, sep=";")
subset_data <- my_data[my_data$Date %in% c("1/2/2007","2/2/2007"),]
subset_data$Global_active_power <- as.numeric(subset_data$Global_active_power)

DataTime <- strptime(paste(subset_data$Date, subset_data$Time), "%d/%m/%Y %H:%M:%S") 
subset_data$Sub_metering_1 <- as.numeric(subset_data$Sub_metering_1)
subset_data$Sub_metering_2 <- as.numeric(subset_data$Sub_metering_2)
subset_data$Sub_metering_3 <- as.numeric(subset_data$Sub_metering_3)
png("plot3.png", width=480, height=480)
plot(DataTime,subset_data$Sub_metering_1, type="l", ylab="Energy sub metering", xlab="")
lines(DataTime,subset_data$Sub_metering_2, type="l", col="red")
lines(DataTime,subset_data$Sub_metering_3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, col=c("black", "red", "blue"))
dev.off()