setwd("C:/Users/alex/Desktop/Exploratory Data Analysis")
options(stringsAsFactors = F)
my_data <- read.table("household_power_consumption.txt", header=T, sep=";")
subset_data <- my_data[my_data$Date %in% c("1/2/2007","2/2/2007"),]
subset_data$Global_active_power <- as.numeric(subset_data$Global_active_power)

DataTime <- strptime(paste(subset_data$Date, subset_data$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
subset_data$Sub_metering_1 <- as.numeric(subset_data$Sub_metering_1)
subset_data$Sub_metering_2 <- as.numeric(subset_data$Sub_metering_2)
subset_data$Sub_metering_3 <- as.numeric(subset_data$Sub_metering_3)
png("plot4.png", width=480, height=480)
par(mfrow=c(2,2))
plot(DataTime,subset_data$Global_active_power,type="l",ylab="Global Active Power",xlab="")
plot(DataTime,subset_data$Voltage,type="l",ylab="Voltage",xlab = "datetime")
plot(DataTime,subset_data$Sub_metering_1, type="l",xlab="",ylab="Energy sub metering")
lines(DataTime,subset_data$Sub_metering_2,col="red")
lines(DataTime,subset_data$Sub_metering_3,col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=, lwd=2.5, col=c("black", "red", "blue"), bty="o")
plot(DataTime,subset_data$Global_reactive_power,type="l",ylab="Global_reactive_power",xlab = "datetime")
dev.off()